### ISSUE TITLE
Enable Back Button in stepper 2 in case user has entered wrong email address and wants correction.

### ISSUE THREAD

**Issue by manjari09** [fguendling/my_repository#10]

**Comment by manjari09** [comment]
Also below scenarios can be considered in this issue:
(1) Enable Next Button only when user's file or document is uploaded successfully else keep it disabled and ask user to upload the document again.
(2) By Wrong email address I mean some typo in his/her email address.

**Comment by manjari09** [comment]
Hey you think this is a valid task.

**Comment by fguendling** [comment]
Yes we can do that

**Comment by fguendling** [comment]
Actually this is related to Issue [#11]

**Comment by manjari09** [comment]
Done
