### ISSUE TITLE
Finalize Landing page and connect to wizard

### ISSUE THREAD

**Issue by fguendling** [fguendling/my_repository#15]

**Comment by fguendling** [comment]
Sections "Preise" and "Angebote" should be included and Buttons in Navigation Bar should be working

**Comment by manjari09** [comment]
Angebote section is done. Please let me know the prototype of Preise Menu.

**Comment by fguendling** [comment]
<img width="1160" alt="Screenshot 2019-09-29 at 22 36 53" src="https://user-images.githubusercontent.com/46090606/65839009-b73dc400-e309-11e9-88c0-33c474968253.png">

**Comment by manjari09** [comment]
This is added.
