### ISSUE TITLE
It must not be possible to return to previous steps in stepper

### ISSUE THREAD

**Issue by fguendling** [fguendling/my_repository#3]
Currently it is possible to return to the first or second step when we are already at step 3.

It should not be possible to go back to a previous step in the stepper.

**Comment by fguendling** [comment]
**Also, it must not be possible to go in forward direction via clicking on the numbers in the stepper.**

**Comment by manjari09** [comment]
Its not a bug by the way. Just an improvement :)

**Comment by fguendling** [comment]
Thk hai

**Comment by fguendling** [comment]
Manjari can you have a look at this?

**Comment by fguendling** [comment]
It is solved now. Solution:
1. stepper has to be linear and
2. mat-steps should have [editable]=false
