### ISSUE TITLE
Development of word count service

### ISSUE THREAD

**Issue by fguendling** [fguendling/my_repository#5]
We need a service, that takes a .docx File as input and provides the number of words of that .docx document as the output. 

Library: Apache POI

**Comment by manjari09** [comment]
Also we need to move service file from Wizard Component to a shared folder. Because in future we will be having more components and we cannot create service class for every component.

**Comment by fguendling** [comment]
Ng App should 
1.) put data into database
2.) send the ID of that database entry via post request to a Java Backend (Microservice)
The Microservice should then 
3.) Send a Get with the ID to the database to get the document
4.) Calculate the word count

After Step 2, the ng-app will continuously send get requests to the Microservice to obtain the word count.

**Comment by fguendling** [comment]
Service is there, results have to be evaluated. There might be updates to this Service in the future.
