### ISSUE TITLE
Create Readme.md which must include the steps to locally run the project with all the prerequisites.

### ISSUE THREAD

**Issue by manjari09** [fguendling/my_repository#6]

**Comment by fguendling** [comment]
I'm working on it but I'm struggling with docker

**Comment by manjari09** [comment]
It's okay , no worries take your time :)

**Comment by fguendling** [comment]
Let me know if the current readme is helpful

**Comment by manjari09** [comment]
I checked the README.md file. Its looking good from Docker perspective. 
Also can we include how to run angular application from installation to finally running the app. Which particular IDE will be good this can also be mentioned in README.md

**Comment by fguendling** [comment]
Still open; Docker compose file has to be fixed.
