### ISSUE TITLE
Update Angular and its respective libraries version to Angular 8.x.x

### ISSUE THREAD

**Issue by manjari09** [fguendling/my_repository#7]

**Comment by manjari09** [comment]
I will update Angular Version okay??

**Comment by fguendling** [comment]
Yes sure

**Comment by manjari09** [comment]
Please take the latest code and see package.json file. Apart from @angular/http all other libraries are updated to 8. Also check if there is any issue resolved or introduced. I have an observation that 'create' thing at stepper 2 is not coming but its coming on stepper 3. :)

**Comment by manjari09** [comment]
Please test by taking latest , I feel like something went wrong from my side due to network problems.

**Comment by manjari09** [comment]
why is this closed , is it working fine?

**Comment by fguendling** [comment]
Yes

**Comment by manjari09** [comment]
I am not able to run locally. Is it like something has been deleted.

**Comment by fguendling** [comment]
<img width="679" alt="Screenshot 2019-09-07 at 12 25 24" src="https://user-images.githubusercontent.com/46090606/64473743-bb434f80-d16a-11e9-9bc9-362d7cc705a1.png">

**Comment by fguendling** [comment]
try ng update --all --force
npm i typescript@3.5.1 --save-dev --save-exact

then delete node_modules and run npm install
